{
    This is a template for the VersionInfoBuild.inc file, which will
    be created, based on this file, during the build process, and will
    contain the latest and up-to-date version information.

    Currently, the variables used in this file are directly
    from the FinalBuilder project. 

    See VersionInfoIDE.inc
}

const
  WORMTAIL_VERSION_MAJOR    = %VersionMajor%;
  WORMTAIL_VERSION_MINOR    = %VersionMinor%;
  WORMTAIL_VERSION_IDENT    = '%VersionIdent%';
  WORMTAIL_VERSION_BUILD    = %VersionBuild%;
  WORMTAIL_VERSION_NAME     = '';
